import psycopg
from project.backend.app.manage.settings import get_settings

neon_db_url = get_settings().neon_db_url

if not neon_db_url:
    raise ValueError(" .env 파일에 NEON_DB_URL이 설정되지 않았습니다. 접속 주소를 확인해주세요.")

def initialize_database():
    print(" Neon DB에 연결 중입니다...")
    conn = None
    cursor = None
    
    try:
        conn = psycopg.connect(neon_db_url)
        cursor = conn.cursor()
        print(" pgvector 확장 프로그램 활성화 중...")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

        cursor.execute("""
        CREATE TABLE IF NOT EXISTS shops (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) UNIQUE NOT NULL,
            domain VARCHAR(255) UNIQUE,
            url TEXT
        );
        """)
        cursor.executemany(
            """
            INSERT INTO shops (name, domain, url)
            VALUES (%s, %s, %s)
            ON CONFLICT (name) DO UPDATE SET
                domain = EXCLUDED.domain,
                url = EXCLUDED.url;
            """,
            [
                ("UNKNOWN", None, None),
                ("FRUITS FAMILY", "fruitsfamily.com", "https://fruitsfamily.com"),
                ("FETCHING", "fetching.co.kr", "https://fetching.co.kr"),
                ("EMPTY", "empty.seoul.kr", "https://empty.seoul.kr"),
                ("WORKSOUT", "worksout.co.kr", "https://worksout.co.kr"),
                ("8DIVISION", "8division.com", "https://8division.com"),
                ("IAMSHOP", "iamshop-online.com", "https://iamshop-online.com"),
                ("THE BOUNCE", "thebounce.co.kr", "https://thebounce.co.kr"),
                ("THE X SHOP", "thexshop.co.kr", "https://thexshop.co.kr"),
                ("COLLECTIV", "collectiv.kr", "https://collectiv.kr"),
                ("KREAM", "kream.co.kr", "https://kream.co.kr"),
                ("MUSINSA", "musinsa.com", "https://musinsa.com"),
                ("EQL", "eqlstore.com", "https://eqlstore.com"),
                ("29CM", "29cm.co.kr", "https://29cm.co.kr"),
                ("Bunjang", "bunjang.co.kr", "https://bunjang.co.kr"),
                ("Danggeun Market", "daangn.com", "https://www.daangn.com"),
                ("Joonggonara", "joongna.com", "https://www.joongna.com"),
                ("ZARA", "zara.com", "https://www.zara.com"),
            ],
        )

        print(" product_db 테이블 생성 중...")
        create_table_query = """
        CREATE TABLE IF NOT EXISTS product_db (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_url TEXT UNIQUE NOT NULL,
            title TEXT NOT NULL,
            title_vector VECTOR(768),
            price NUMERIC(12, 2),
            currency VARCHAR(3) NOT NULL DEFAULT 'KRW',
            brand TEXT NOT NULL,
            category VARCHAR(20) NOT NULL,
            is_soldout BOOLEAN,
            image_url TEXT NOT NULL,
            image_vector VECTOR(768), 
            shop_id INTEGER NOT NULL,
            gender TEXT NOT NULL,
            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_product_db_shop_id_shops
                FOREIGN KEY (shop_id) REFERENCES shops(id)
                ON DELETE RESTRICT
        );
        """
        cursor.execute(create_table_query)
        conn.commit()
        print("데이터베이스 스키마 세팅이 완벽하게 완료되었습니다!")

    except Exception as e:
        print(f" 에러 발생: {e}")
        if conn:
            conn.rollback()
            if cursor:
                cursor.close()
    finally:
        if cursor: cursor.close()
        if conn: conn.close()
        print(" DB 연결을 종료했습니다.")

if __name__ == "__main__":
    initialize_database()
