import psycopg
from project.backend.app.manage.settings import get_settings

neon_db_url = get_settings().neon_db_url

if not neon_db_url:
    raise ValueError(" .env 파일에 NEON_DB_URL이 설정되지 않았습니다. 접속 주소를 확인해주세요.")

def initialize_database():
    print(" Neon DB에 연결 중입니다...")
    conn = None
    cursor = None
    
    try:
        conn = psycopg.connect(neon_db_url)
        cursor = conn.cursor()
        print(" pgvector 확장 프로그램 활성화 중...")
        cursor.execute("CREATE EXTENSION IF NOT EXISTS vector;")

        cursor.execute("""
        CREATE TABLE IF NOT EXISTS shops (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name VARCHAR(100) UNIQUE NOT NULL
        );
        """)
        cursor.executemany(
            "INSERT INTO shops (name) VALUES (%s) ON CONFLICT (name) DO NOTHING;",
            [(name,) for name in (
                "UNKNOWN", "FRUITS FAMILY", "FETCHING", "EMPTY", "WORKSOUT",
                "8DIVISION", "IAMSHOP", "THE BOUNCE", "THE X SHOP", "COLLECTIV",
                "KREAM", "MUSINSA", "EQL", "29CM", "Bunjang",
                "Danggeun Market", "Joonggonara", "ZARA",
            )],
        )

        print(" product_db 테이블 생성 중...")
        create_table_query = """
        CREATE TABLE IF NOT EXISTS product_db (
            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            source_url TEXT NOT NULL,
            title TEXT NOT NULL,
            title_vector VECTOR(768),
            price NUMERIC(12, 2),
            brand TEXT NOT NULL,
            category VARCHAR(20) NOT NULL,
            is_soldout BOOLEAN,
            image_url TEXT NOT NULL,
            image_vector VECTOR(768), 
            shop_id INTEGER NOT NULL,
            gender TEXT NOT NULL,
            created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
            CONSTRAINT fk_product_db_shop_id_shops
                FOREIGN KEY (shop_id) REFERENCES shops(id)
                ON DELETE RESTRICT,
            UNIQUE(source_url, title)
        );
        """
        cursor.execute(create_table_query)
        conn.commit()
        print("데이터베이스 스키마 세팅이 완벽하게 완료되었습니다!")

    except Exception as e:
        print(f" 에러 발생: {e}")
        if conn:
            conn.rollback()
            if cursor:
                cursor.close()
    finally:
        if cursor: cursor.close()
        if conn: conn.close()
        print(" DB 연결을 종료했습니다.")

if __name__ == "__main__":
    initialize_database()
