from collections.abc import AsyncGenerator
from typing import Any, Awaitable, Callable
from fastapi import HTTPException
from psycopg import InterfaceError, OperationalError
from psycopg_pool import AsyncConnectionPool

async def init_db(db_pool: AsyncConnectionPool) -> None:
    try:
        async with db_pool.connection() as conn:
            async with conn.cursor() as cursor:
                await cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS event_logs (
                            id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            user_id INTEGER,
                            action VARCHAR(50) NOT NULL,
                            entity_type VARCHAR(50) NOT NULL,
                            entity_id TEXT,
                            metadata JSONB DEFAULT '{}'::jsonb,
                            occurred_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT fk_event_logs_user_id_users
                                FOREIGN KEY (user_id) REFERENCES users(id)
                                ON DELETE SET NULL
                            );
                    """
                )
                await cursor.execute(
                    "CREATE INDEX IF NOT EXISTS idx_event_logs_user_action ON event_logs (user_id, action);"
                )
                await cursor.execute(
                    "CREATE INDEX IF NOT EXISTS idx_event_logs_entity ON event_logs (entity_type, entity_id);"
                )

                await cursor.execute(
                    """
                    CREATE TABLE IF NOT EXISTS saved_posts (
                            product_id INTEGER NOT NULL,
                            user_id INTEGER NOT NULL,
                            likes INTEGER NOT NULL DEFAULT 0,
                            dislikes INTEGER NOT NULL DEFAULT 0,
                            created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
                            PRIMARY KEY (user_id, product_id),
                            CONSTRAINT fk_saved_posts_product_id_product_db
                                FOREIGN KEY (product_id) REFERENCES product_db(id)
                                ON DELETE CASCADE,
                            CONSTRAINT fk_saved_posts_user_id_users
                                FOREIGN KEY (user_id) REFERENCES users(id)
                                ON DELETE CASCADE
                            );
                    """
                )

                await conn.commit()
        print("DB 테이블 초기화 완료")
    except Exception as exc:
        print(f"DB 초기화 중 경고: {exc}")

def create_db_pool(conninfo: str, min_size: int = 5, max_size: int = 20) -> AsyncConnectionPool:
    return AsyncConnectionPool(conninfo=conninfo, min_size=min_size, max_size=max_size)

async def _ping_connection(conn: Any) -> None:
    async with conn.cursor() as cursor:
        await cursor.execute("SELECT 1")
        await cursor.fetchone()

async def get_db_connection(
    pool: AsyncConnectionPool | None,
    recreate_pool: Callable[[], Awaitable[AsyncConnectionPool]] | None = None,
) -> AsyncGenerator[Any, None]:
    current_pool = pool

    for attempt in range(2):
        if current_pool is None or current_pool.closed:
            if recreate_pool is None:
                raise HTTPException(status_code=500, detail="Database pool is not initialized")
            current_pool = await recreate_pool()

        conn = None
        pool_used = current_pool
        try:
            conn = await pool_used.getconn()
            await _ping_connection(conn)
            try:
                yield conn
            except Exception:
                if not getattr(conn, "closed", False):
                    await conn.rollback()
                raise
            return
        except (OperationalError, InterfaceError) as exc:
            if conn is not None:
                try:
                    await conn.close()
                except Exception:
                    pass

            if recreate_pool is None or attempt == 1:
                raise HTTPException(
                    status_code=500,
                    detail=f"Database connection is unavailable: {exc}",
                ) from exc

            current_pool = await recreate_pool()
        finally:
            if conn is not None and not getattr(conn, "closed", False):
                await pool_used.putconn(conn)

    raise HTTPException(status_code=500, detail="Database connection is unavailable")
